plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

java {
}
repositories {
    maven { url = 'https://maven.brott.dev/' }
    mavenCentral()
}

dependencies {
    implementation 'com.acmerobotics.roadrunner:MeepMeep:0.1.6'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}
kotlin {
    jvmToolchain(8)
}